<script setup lang="ts">
import {computed,ref,watch,nextTick,onMounted,onBeforeUnmount} from 'vue';
import {UiButton,UiSelect,UiPanel,UiTabs} from './ui';
import {admissions as a,fmt,type Institute} from '../data';
import {rules,departments,programRows,availablePrograms,allPrograms,programMetrics,metricLabels,metricUnits,csvEncode,type Level,type Metric,type Section,type Program} from '../admissions';
import InstituteBadge from './InstituteBadge.vue';
import {instituteStyle} from '../identity';
import Icon from './Icon.vue';
import LineChart from './LineChart.vue';
import ProgramList from './admissions/ProgramList.vue';
import Geography from './admissions/Geography.vue';
import UniversityScores from './admissions/UniversityScores.vue';
import '../design/admissions.css';
const props=withDefaults(defineProps<{initialInstitute?:string}>(),{initialInstitute:'all'});
defineEmits<{institute:[value:Institute];topic:[id:string];program:[value:Program]}>();
type Detail={kind:'department'|'program'|'quota'|'region';id:string}|null;
type State={section:Section;level:Level;year:number;selected:string;metric:Metric;mode:string;sort:string;composition:string;detail:Detail};
const defaults=():State=>({section:'overview',level:'ВО',year:2026,selected:'all',metric:'applications',mode:'leaders',sort:'desc',composition:'quotas',detail:null});
const key='rut-admissions-state-v1';
function restored(){try{const s=JSON.parse(sessionStorage.getItem(key)||'null');if(s&&['ВО','СПО'].includes(s.level)&&a.years.includes(s.year)&&['overview','departments','programs','composition','quality'].includes(s.section))return {...defaults(),...s} as State;}catch{}return defaults();}
const state=ref<State>(restored());const trail=ref<{state:State;scroll:number}[]>([]);const notice=ref('');const root=ref<HTMLElement>();const heading=ref<HTMLElement>();const showDefinitions=ref(false);
const s=computed(()=>state.value);const current=computed(()=>s.value.year===2026);const vo=computed(()=>s.value.level==='ВО');
const departmentOptions=computed(()=>departments(s.value.level));
const selectedName=computed(()=>departmentOptions.value.find(i=>i.id===s.value.selected)?.short??'Все подразделения');
const rows=computed(()=>departmentOptions.value.filter(i=>s.value.selected==='all'||i.id===s.value.selected).slice().sort((x,y)=>s.value.sort==='desc'?y.enrolled-x.enrolled:x.enrolled-y.enrolled));
const top=computed(()=>departmentOptions.value.slice().sort((x,y)=>y.enrolled-x.enrolled).slice(0,5));
const departmentTotal=computed(()=>departmentOptions.value.reduce((sum,item)=>sum+item.enrolled,0));
const departmentLeader=computed(()=>departmentOptions.value.slice().sort((x,y)=>y.enrolled-x.enrolled)[0]);
const departmentMax=computed(()=>Math.max(...departmentOptions.value.map(item=>item.enrolled),1));
const departmentCoverage=computed(()=>{const total=vo.value?enrollment.value:a.college.enrolled;return total?departmentTotal.value/total*100:0;});
function departmentShare(enrolled:number,students:number){return students?enrolled/students*100:0;}
const programs=computed(()=>programRows(s.value.level,s.value.metric,s.value.mode,s.value.selected));
const department=computed(()=>s.value.detail?.kind==='department'?departmentOptions.value.find(d=>d.id===s.value.detail!.id):undefined);
const program=computed(()=>s.value.detail?.kind==='program'?allPrograms.find(p=>p.id===s.value.detail!.id):undefined);
const quotaRows=computed(()=>vo.value?rules.quotas:[{id:'priority',name:'Первоочередной приём',label:'Участники СВО и члены их семей',...a.college.priority}]);
const quotaTotal=computed(()=>quotaRows.value.reduce((sum,q)=>sum+q.value,0));
const svoQuota=computed(()=>quotaRows.value.find(q=>q.id===(vo.value?'separate':'priority'))?.value??0);
const svoShare=computed(()=>quotaTotal.value?svoQuota.value/quotaTotal.value*100:0);
const quota=computed(()=>quotaRows.value.find(q=>s.value.detail?.kind==='quota'&&q.id===s.value.detail.id));
const sectionNames:Record<Section,string>={overview:'Обзор',departments:'Подразделения',programs:'Программы',composition:'Состав набора',quality:'Качество набора'};
const tabs=[{value:'overview' as Section,label:'Обзор'},{value:'departments' as Section,label:'Подразделения'},{value:'programs' as Section,label:'Программы'},{value:'composition' as Section,label:'Состав набора'}];
const title=computed(()=>department.value?.name||program.value?.name||quota.value?.name||(s.value.detail?.kind==='region'?s.value.detail.id:sectionNames[s.value.section]));
const source=computed(()=>!vo.value?rules.sources.college:s.value.section==='quality'||department.value?rules.sources.overview+'; '+rules.sources.programs:s.value.section==='programs'||program.value?rules.sources.programs:rules.sources.overview);
const sourceNote=computed(()=>!vo.value?'С6 · итоги СПО':s.value.section==='quality'||department.value?'С4–С5 · итоги и программы ВО':s.value.section==='programs'||program.value?'С5 · программы ВО':'С4 · итоги ВО');
const enrollment=computed(()=>vo.value?a.enrollmentHistory[a.years.indexOf(s.value.year)]??null:current.value?a.college.enrolled:null);
const exam=computed(()=>vo.value?a.scoreHistory[a.years.indexOf(s.value.year)]??null:null);
function snapshot(){return JSON.parse(JSON.stringify(state.value)) as State;}
function scrollContainer(){return root.value?.closest<HTMLElement>('.page-workspace');}
function scrollY(){return scrollContainer()?.scrollTop||window.scrollY;}
function moveScroll(top:number){const host=scrollContainer();if(host&&host.scrollHeight>host.clientHeight)host.scrollTo({top});else window.scrollTo({top});}
async function navigate(patch:Partial<State>){trail.value.push({state:snapshot(),scroll:scrollY()});state.value={...state.value,detail:null,...patch};await nextTick();moveScroll(0);heading.value?.focus({preventScroll:true});}
async function back(){notice.value='';const old=trail.value.pop();if(!old){await navigate({section:'overview',detail:null});trail.value=[];return;}state.value=old.state;await nextTick();moveScroll(old.scroll);heading.value?.focus({preventScroll:true});}
function tab(section:Section){const compatible=section==='departments'||section==='programs';if(!compatible&&s.value.selected!=='all'){notice.value='Фильтр подразделения сброшен: этот экран показывает весь набор.';}navigate({section,...(!compatible?{selected:'all'}:{})});trail.value=[];}
function departmentByShort(short:string){return departmentOptions.value.find(d=>d.short===short);}
function openDepartment(id:string){navigate({detail:{kind:'department',id}});}
function openShort(short:string){const d=departmentByShort(short);if(d)openDepartment(d.id);}
function openProgram(p:Program){navigate({detail:{kind:'program',id:p.id}});}
function openQuota(id:string){navigate({section:'composition',composition:'quotas',detail:{kind:'quota',id}});}
function openRegion(name:string){navigate({section:'composition',composition:'geography',detail:{kind:'region',id:name}});}
function selectYear(value:string|number){const year=Number(value);navigate({year,detail:null});notice.value=year===2026?'':`За ${year} год доступны только общие ряды ВО: зачисление и ЕГЭ. Детализация не предоставлена.`;}
function yearPoint(index:number){const year=a.years[index]!;navigate({year,section:'departments',detail:null});notice.value=year===2026?'':`Зачислено ${fmt(a.enrollmentHistory[index]!)} человек, все формы. Разбивки по подразделениям за ${year} год нет.`;}
function changeLevel(value:string|number){const previous=state.value;const level=value as Level;state.value={...defaults(),level,year:previous.year,section:previous.section==='quality'?'overview':previous.section};trail.value=[];notice.value='Фильтры сброшены при смене уровня образования. Год сохранён.';}
function resetFilters(){state.value={...state.value,selected:'all',sort:'desc',metric:'applications',mode:'leaders',detail:null};notice.value='Локальные фильтры сброшены. Год и уровень образования сохранены.';}
function externalContext(id:string){state.value={...defaults(),section:id==='all'?'overview':'departments',selected:id};trail.value=[];}
watch(()=>props.initialInstitute,externalContext);if(props.initialInstitute!=='all')externalContext(props.initialInstitute);
watch(state,value=>{try{sessionStorage.setItem(key,JSON.stringify(value));}catch{}},{deep:true});
function keydown(event:KeyboardEvent){if(event.key==='Escape'&&s.value.detail){event.stopPropagation();back();}}
onMounted(()=>root.value?.addEventListener('keydown',keydown));onBeforeUnmount(()=>root.value?.removeEventListener('keydown',keydown));
const foreignText='Нет данных об иностранных гражданах, зачисленных в выбранном году.';
function visibleProgramMetrics(p:Program):Partial<Record<Metric,number|null>>{const metrics=programMetrics(p);return vo.value?metrics:{applications:metrics.applications,competition:metrics.competition};}
const metricNames:Record<Metric,string>={applications:'Заявления',competition:'Конкурс на бюджет',score:'ЕГЭ · бюджет'};
function regionValue(name:string){return name==='Москва и МО'?(vo.value?a.moscow:a.college.moscow):name==='Другие регионы'?(vo.value?a.otherRegions:a.college.otherRegions):a.regions.find(r=>r.name===name)?.value??null;}
function sparkPoints(values:number[]){const source=values.length>1?values:[values[0]??0,values[0]??0];const min=Math.min(...source),max=Math.max(...source),range=max-min||1;return source.map((value,index)=>({x:3+index*(94/Math.max(source.length-1,1)),y:33-(value-min)/range*30}));}
function miniSpark(values:number[]){const points=sparkPoints(values);let path=`M ${points[0]!.x} ${points[0]!.y}`;for(let index=1;index<points.length;index++){const previous=points[index-1]!,point=points[index]!,middle=(previous.x+point.x)/2;path+=` C ${middle} ${previous.y}, ${middle} ${point.y}, ${point.x} ${point.y}`;}return path;}
function miniSparkArea(values:number[]){return `${miniSpark(values)} L 97 36 L 3 36 Z`;}
function miniSparkEnd(values:number[]){return sparkPoints(values).at(-1)!.y;}
function scenario(destination:string){if(destination==='target')openQuota('target');else if(destination==='geography'||destination==='foreign')navigate({section:'composition',composition:destination});else navigate({section:destination as Section});}
function exportData(){
 const rowsOut:(string|number|null)[][]=[['Раздел',title.value],['Год',s.value.year],['Уровень',s.value.level],['Подразделение',selectedName.value],['Порядок',s.value.sort==='desc'?'По убыванию зачисления':'По возрастанию зачисления'],['Режим',s.value.section==='programs'?(s.value.mode==='new'?'Новые программы':metricLabels[s.value.metric]):s.value.section==='composition'?s.value.composition:sectionNames[s.value.section]],['Источник',source.value],['Обновлено',rules.updated],[]];
 const add=(name:string,value:number|string|null,unit:string,scope:string)=>rowsOut.push([name,value,unit,scope]);
 if(program.value){const p=program.value;rowsOut.push(['Программа',p.name],['Подразделение программы',p.institute]);for(const [k,v] of Object.entries(visibleProgramMetrics(p)))add(metricNames[k as Metric],v,metricUnits[k as Metric],'2026 · соответствующий рейтинг');for(const n of ['Зачислено','План'])add(n,null,'чел.','Нет данных');}
 else if(department.value){rowsOut.push(['Подразделение','Общая численность, чел.','Зачислено, чел.','Охват']);const d=department.value;rowsOut.push([d.short,d.students,d.enrolled,vo.value?'Очная форма':'Форма не указана']);rowsOut.push([],['Программа','Подразделение','Показатель','Значение','Единица']);availablePrograms(s.value.level,d.id).forEach(p=>rowsOut.push([p.name,p.institute,p.metric?metricNames[p.metric as Metric]:'Новая программа',p.value??null,p.metric?metricUnits[p.metric as Metric]:'Нет данных']));}
 else if(quota.value){add(quota.value.name,quota.value.value,'чел.','2026');add('Изменение',quota.value.change,'%','Из источника · к прошлому году');quota.value.categories.forEach(c=>add(c,null,'чел.','Разбивка категории не предоставлена'));if(quota.value.id==='target'){add('Места ОАО «РЖД»',rules.target.places,'мест','2026');add('Изменение мест ОАО «РЖД»',rules.target.placesChange,'мест','К предыдущему году');add('Зачисление ОАО «РЖД»',null,'чел.','Нет данных');}}
 else if(s.value.detail?.kind==='region'){add(s.value.detail.id,regionValue(s.value.detail.id),'чел.','2026');add('Подразделения и программы',null,'','Разбивка не предоставлена');}
 else if(!current.value){if(vo.value){add('Зачислено',enrollment.value,'чел.','Все формы');add('Средний балл ЕГЭ',exam.value,'балла','Бюджет');}add('Детализация',null,'','За выбранный год не предоставлена');}
 else if(s.value.section==='departments'){rowsOut.push(['Подразделение','Общая численность, чел.','Зачислено, чел.','Охват']);rows.value.forEach(d=>rowsOut.push([d.short,d.students,d.enrolled,vo.value?'Очная форма':'Форма не указана']));}
 else if(s.value.section==='programs'&&!vo.value&&s.value.metric==='competition'){add('Общий конкурс на бюджет СПО',a.college.competition,'чел./место','2026 · весь набор СПО');add('Рейтинг по программам',null,'','Не предоставлен');}
 else if(s.value.section==='programs'){rowsOut.push(['Программа','Подразделение','Значение','Единица','Уровень программы']);programs.value.forEach(p=>rowsOut.push([p.name,p.institute,p.value??null,p.metric?metricUnits[p.metric as Metric]:'Нет данных',p.level??'']));if(!programs.value.length)add('Записи',null,'','В доступном топе отсутствуют');}
 else if(s.value.section==='composition'){if(s.value.composition==='quotas'){quotaRows.value.forEach(q=>{add(q.name,q.value,'чел.','2026');add(q.name+' · изменение',q.change,'%','Из источника · к прошлому году');});if(vo.value){add('Места ОАО «РЖД»',110,'мест','2026');add('Изменение мест ОАО «РЖД»',-180,'мест','К предыдущему году');}}else if(s.value.composition==='foreign')add('Иностранные граждане',null,'чел.','Данные кампании отсутствуют');else{for(const name of ['Москва и МО','Другие регионы'])add(name,regionValue(name),'чел.','Все зачисленные географического среза');add('Москва и МО · доля',vo.value?66:82,'%','Географический срез');add('Другие регионы · доля',vo.value?34:18,'%','Географический срез');if(vo.value)a.regions.forEach(r=>add(r.name,r.value,'чел.','Топ-5 вне Москвы и МО'));}}
 else if(s.value.section==='quality'){add('ЕГЭ · бюджет',a.score,'балла','2026');add('ЕГЭ · бюджет и платное',a.scoreAll,'балла','2026');a.years.forEach((y,i)=>add('ЕГЭ '+y,a.scoreHistory[i]!,'балла','Бюджет'));rules.quality.universities.forEach(u=>add(u.name,u.value,'балла','Бюджет · 2026'));add('Россия',a.nationalScore2025,'балла','2025 · другой период');programRows('ВО','score').forEach(p=>add(p.name,p.value??null,'балла','Технический топ-5'));add('Победители и призёры олимпиад',5,'чел.','2026');add('Максимальный конкурсный балл',300,'баллов','290 ЕГЭ + 10 достижений · ВИШ');}
 else{add('Заявления',vo.value?'28 тыс.':'8,3 тыс.','заявлений','2026 · округлено');add('Зачислено',vo.value?a.enrolled:'1,39 тыс.','чел.',vo.value?'Все формы':'Округлённо');add(vo.value?'ЕГЭ · бюджет':'Конкурс на бюджет',vo.value?a.score:a.college.competition,vo.value?'балла':'чел./место','2026');if(vo.value){a.years.forEach((y,i)=>{add('Зачислено '+y,a.enrollmentHistory[i]!,'чел.','Все формы');add('ЕГЭ '+y,a.scoreHistory[i]!,'балла','Бюджет');});}top.value.forEach(d=>add(d.short,d.enrolled,'чел.',vo.value?'Топ-5 · очная форма':'По колледжам'));quotaRows.value.forEach(q=>{add(q.name,q.value,'чел.','2026');add(q.name+' · изменение',q.change,'%','Из источника · к прошлому году');});for(const name of ['Москва и МО','Другие регионы'])add(name,regionValue(name),'чел.','Географический срез');add('Приём по квотам',quotaTotal.value,'чел.','Включая целевой приём');add('СВО и семьи · доля квот',svoShare.value,'%','От общего приёма по квотам');if(vo.value)rules.quality.universities.forEach(u=>add(u.name,u.value,'балла','ЕГЭ · бюджет · 2026'));add('Рост заявлений',vo.value?a.applicationGrowth:a.college.applicationGrowth,'%','Из источника · к прошлому году');if(vo.value){add('Рост ЕГЭ',a.scoreGrowth,'балла','Бюджет · к прошлому году');add('Победители и призёры олимпиад',a.olympiads,'чел.','2026');a.regions.forEach(r=>add(r.name,r.value,'чел.','Топ-5 вне Москвы и МО'));}else{add('Рост зачисления',a.college.growth,'%','Из источника · к прошлому году');a.college.programs.forEach(p=>add(p.name,p.value,'заявлений','Топ-6 · СПО'));}add('Москва и МО · доля',vo.value?66:82,'%','Из источника · географический срез');add('Другие регионы · доля',vo.value?34:18,'%','Из источника · географический срез');}
 const url=URL.createObjectURL(new Blob([csvEncode(rowsOut)],{type:'text/csv;charset=utf-8;'}));const link=document.createElement('a');link.href=url;link.download=`RUT.digital-прием-${s.value.year}-${s.value.level}-${s.value.detail?.kind??s.value.section}.csv`;link.click();URL.revokeObjectURL(url);
}
</script>
<template><div ref="root" class="admissions-dashboard">
 <div class="ad-context"><div><span class="ad-eyebrow">ПРИЁМНАЯ КАМПАНИЯ</span><h2 ref="heading" tabindex="-1">{{title}}</h2></div><div class="ad-controls"><label>Год<UiSelect :model-value="s.year" aria-label="Год кампании" @update:model-value="selectYear"><option v-for="year in a.years" :key="year" :value="year">{{year}}</option></UiSelect></label><label>Образование<UiSelect :model-value="s.level" aria-label="Уровень образования" @update:model-value="changeLevel"><option value="ВО">ВО · Высшее</option><option value="СПО">СПО · Колледжи</option></UiSelect></label><UiButton variant="secondary" @click="exportData"><Icon name="download" :size="18"/> CSV</UiButton></div></div>
 <div class="ad-navigation"><UiTabs :model-value="s.section" :items="tabs" label="Разделы приёмной кампании" @update:model-value="tab"/><div class="ad-meta"><span>{{rules.updated}}</span><UiButton class="ad-text-link" @click="showDefinitions=!showDefinitions">О данных <Icon name="info" :size="15"/></UiButton></div></div>
 <div v-if="notice" class="ad-notice" role="status"><span>{{notice}}</span><UiButton aria-label="Закрыть уведомление" @click="notice=''"><Icon name="close" :size="16"/></UiButton></div>
 <div v-if="s.selected!=='all'||s.metric!=='applications'||s.mode!=='leaders'||s.sort!=='desc'" class="ad-active-filters"><span>Фильтры:</span><b v-if="s.selected!=='all'">{{selectedName}}</b><b v-if="s.section==='programs'">{{s.mode==='new'?'Новые программы':metricLabels[s.metric]}}</b><b v-if="s.sort==='asc'">По возрастанию зачисления</b><UiButton @click="resetFilters">Сбросить</UiButton></div>
 <UiPanel v-if="showDefinitions" class="ad-definitions" title="О данных и расчётах"><p>Срез: {{rules.updated}}. Точная дата обновления, владелец и периодичность обновления требуют согласования.</p><p>Источники: {{rules.sources.overview}}; {{rules.sources.programs}}; {{rules.sources.college}}. Изменения воспроизведены из исходных материалов; они не означают оценку результата. Причины изменений не установлены.</p><dl><template v-for="definition in rules.definitions" :key="definition.name"><dt>{{definition.name}}</dt><dd>{{definition.rule}}</dd></template></dl><h3>Недостающие данные</h3><ul><li v-for="request in rules.requests" :key="request">{{request}}</li></ul><p>Статусы отклонений и выполнение плана появятся после согласования планов и критериев. Решения о приёме, финансировании и продвижении принимаются после проверки ресурсов и причин результата.</p></UiPanel>
 <div v-if="trail.length||s.detail||s.section==='quality'" class="ad-breadcrumb"><UiButton variant="secondary" @click="back"><Icon name="left" :size="16"/>Назад<span v-if="program"> к {{trail.at(-1)?.state.detail?.kind==='department'?'подразделению':'рейтингу'}}</span></UiButton><span>{{s.year}} / {{s.level}} / {{sectionNames[s.section]}}<template v-if="program && trail.at(-1)?.state.detail?.kind==='department'"> / {{program.institute}}</template></span></div>

 <UiPanel v-if="!current && (s.section!=='overview'&&s.section!=='quality'||!vo)" title="Нет детализации за выбранный год" class="ad-missing-year"><div v-if="vo" class="ad-summary-pair"><div><strong>{{fmt(enrollment!)}}</strong><span>зачислено · все формы · {{s.year}}</span></div><div><strong>{{fmt(exam!)}}</strong><span>ЕГЭ · бюджет · {{s.year}}</span></div></div><p>Разбивки {{s.section==='departments'?'по подразделениям':s.section==='programs'?'по программам':'состава набора'}} за {{s.year}} год не предоставлены. </p><UiButton variant="secondary" @click="selectYear(2026)">Открыть данные 2026 года</UiButton></UiPanel>

 <template v-else-if="s.detail">
  <template v-if="department"><UiPanel title="Показатели подразделения" :description="`${s.year} · ${s.level} · ${vo?'Очная форма':'Форма обучения в источнике не указана'}`"><div class="ad-summary-pair"><div><strong>{{fmt(department.enrolled)}}</strong><span>зачислено в {{s.year}} году</span></div><div><strong>{{fmt(department.students)}}</strong><span>общая численность студентов · {{vo?'очно':'все доступные данные'}}</span></div></div><p class="ad-empty">История набора и план мест пока недоступны.</p></UiPanel><UiPanel title="Доступные программы подразделения" description="Программы-лидеры и новые направления"><ProgramList :items="availablePrograms(s.level,department.id)" :college="!vo" @program="openProgram" @department="openShort"/></UiPanel></template>
  <template v-else-if="program"><UiPanel title="Показатели программы" :description="`${program.institute} · ${s.year} · ${program.level||s.level}`"><div class="ad-program-metrics"><div v-for="(value,key) in visibleProgramMetrics(program)" :key="key"><span>{{metricNames[key]}}</span><strong>{{value==null?'Нет данных':fmt(value)}}</strong><small>{{metricUnits[key]}}</small></div></div><p v-if="program.level" class="ad-empty">Новая программа · статистика набора пока недоступна.</p><p v-else class="ad-empty">Показатели доступны только для указанного рейтинга.</p><div class="ad-availability"><span>Динамика <b>Нет данных</b></span><span>Зачисление <b>Нет данных</b></span><span>План мест <b>Нет данных</b></span></div><div class="ad-detail-actions"><UiButton variant="secondary" @click="openShort(program.institute)">К подразделению <Icon name="right" :size="16"/></UiButton><UiButton variant="secondary" @click="back">{{trail.at(-1)?.state.detail?.kind==='department'?'Назад к подразделению':'Назад к рейтингу'}}</UiButton></div></UiPanel></template>
  <template v-else-if="quota"><UiPanel title="Результат приёма" :description="`${quota.label} · ${s.year} · ${s.level}`"><div class="ad-detail-number"><strong>{{fmt(quota.value)}}</strong><span>зачислено, человек</span><b v-if="quota.change!==null">{{quota.change>0?'+':''}}{{fmt(quota.change)}}% к прошлому году · источник</b></div><template v-if="quota.id!=='target'"><h3>Категории</h3><ul class="ad-category-list"><li v-for="category in quota.categories" :key="category">{{category}}</li></ul><p class="ad-empty">Распределение {{quota.value}} зачисленных по перечисленным категориям, подразделениям и программам не предоставлено. </p></template><p class="ad-empty">История и план квоты пока недоступны.</p></UiPanel><UiPanel v-if="quota.id==='target'" title="Целевой приём по заказчикам" description="2026 · зачисленные и предложенные места"><div class="ad-table-wrap"><table><thead><tr><th>Заказчик</th><th>Предложено мест · 2026</th><th>Изменение мест</th><th>Зачислено</th></tr></thead><tbody><tr><th>{{rules.target.customer}}</th><td>110</td><td>−180</td><td>Нет данных</td></tr></tbody></table></div><p>217 — весь целевой набор. 110 мест — предложение РЖД.</p><p class="ad-empty">Зачисление по заказчикам пока недоступно.</p><h3>Исполнение обязательств</h3><p>{{rules.target.obligationsStatus}}</p></UiPanel></template>
  <UiPanel v-else-if="s.detail.kind==='region'" title="Набор из региона" :description="`${s.year} · ${s.level} · география набора`"><div class="ad-detail-number"><strong>{{regionValue(s.detail.id)===null?'Нет данных':fmt(regionValue(s.detail.id)!)}}</strong><span>зачислено, человек</span></div><p class="ad-empty">Распределение набора из {{s.detail.id==='Москва и МО'?'Москвы и Московской области':s.detail.id==='Другие регионы'?'других регионов':'этого региона'}} по подразделениям и программам не предоставлено. </p></UiPanel>
 </template>

 <template v-else-if="s.section==='overview'">
  <div class="ad-kpis">
   <UiButton class="ad-kpi ad-kpi--applications" :class="{'ad-kpi-missing':!current}" @click="navigate({section:'programs',metric:'applications',mode:'leaders',selected:'all'})">
    <span class="ad-kpi-head"><b>Подано заявлений</b><i><Icon name="source" :size="21"/></i></span>
    <strong>{{current?(vo?'28':'8,3'):'Нет данных'}}<small v-if="current">тыс.</small></strong>
    <span v-if="current" class="ad-kpi-meta"><em class="ad-kpi-delta"><Icon :name="(vo?a.applicationGrowth:a.college.applicationGrowth)>=0?'up':'downArrow'" :size="15"/>{{(vo?a.applicationGrowth:a.college.applicationGrowth)>0?'+':''}}{{fmt(vo?a.applicationGrowth:a.college.applicationGrowth)}}%</em><small>к 2025 году</small></span><em v-else class="ad-kpi-note">История не предоставлена</em>
    <span v-if="current" class="ad-kpi-spark-wrap" :style="{'--spark-y':miniSparkEnd([100,vo?128:102.6])/36*100+'%'}"><svg class="ad-kpi-spark" viewBox="0 0 100 36" preserveAspectRatio="none" aria-hidden="true"><path class="ad-kpi-spark-area" :d="miniSparkArea([100,vo?128:102.6])"/><path class="ad-kpi-spark-line" :d="miniSpark([100,vo?128:102.6])"/></svg><i class="ad-kpi-spark-dot" aria-hidden="true"></i></span>
   </UiButton>
   <UiButton class="ad-kpi ad-kpi--primary" @click="navigate({section:'departments',selected:'all',sort:'desc'})">
    <span class="ad-kpi-head"><b>Зачислено студентов</b><i><Icon name="admissions" :size="22"/></i></span>
    <strong>{{vo?fmt(enrollment!):'1,39'}}<small v-if="!vo">тыс.</small></strong>
    <em class="ad-kpi-note">{{vo?'Все формы обучения':'+3,3% · округлённо'}}</em>
    <span class="ad-kpi-spark-wrap" :style="{'--spark-y':miniSparkEnd(vo?a.enrollmentHistory.slice(0,a.years.indexOf(s.year)+1):[100,100+a.college.growth])/36*100+'%'}"><svg class="ad-kpi-spark" viewBox="0 0 100 36" preserveAspectRatio="none" aria-hidden="true"><path class="ad-kpi-spark-area" :d="miniSparkArea(vo?a.enrollmentHistory.slice(0,a.years.indexOf(s.year)+1):[100,100+a.college.growth])"/><path class="ad-kpi-spark-line" :d="miniSpark(vo?a.enrollmentHistory.slice(0,a.years.indexOf(s.year)+1):[100,100+a.college.growth])"/></svg><i class="ad-kpi-spark-dot" aria-hidden="true"></i></span>
   </UiButton>
   <UiButton class="ad-kpi ad-kpi--score" @click="vo?navigate({section:'quality'}):navigate({section:'programs',metric:'competition',mode:'leaders'})">
    <span class="ad-kpi-head"><b>{{vo?'Средний балл ЕГЭ':'Конкурс на бюджет'}}</b><i><Icon name="trend" :size="21"/></i></span>
    <strong>{{vo?fmt(exam!):'7,2'}}</strong>
    <span v-if="vo&&current" class="ad-kpi-meta"><em class="ad-kpi-delta"><Icon :name="a.scoreGrowth>=0?'up':'downArrow'" :size="15"/>{{a.scoreGrowth>0?'+':''}}{{fmt(a.scoreGrowth)}}</em><small>к 2025 году</small></span><em v-else class="ad-kpi-note">{{vo?'Бюджет · '+s.year:'чел./место'}}</em>
    <span class="ad-kpi-spark-wrap" :style="{'--spark-y':miniSparkEnd(vo?a.scoreHistory.slice(0,a.years.indexOf(s.year)+1):[0,a.college.competition])/36*100+'%'}"><svg class="ad-kpi-spark" viewBox="0 0 100 36" preserveAspectRatio="none" aria-hidden="true"><path class="ad-kpi-spark-area" :d="miniSparkArea(vo?a.scoreHistory.slice(0,a.years.indexOf(s.year)+1):[0,a.college.competition])"/><path class="ad-kpi-spark-line" :d="miniSpark(vo?a.scoreHistory.slice(0,a.years.indexOf(s.year)+1):[0,a.college.competition])"/></svg><i class="ad-kpi-spark-dot" aria-hidden="true"></i></span>
   </UiButton>
   <UiButton class="ad-kpi ad-kpi--region" :class="{'ad-kpi-missing':!current}" @click="navigate({section:'composition',composition:'geography'})">
    <span class="ad-kpi-head"><b>Вне Москвы и МО</b><i><Icon name="pin" :size="21"/></i></span>
    <strong>{{current?(vo?'34%':'18%'):'Нет данных'}}</strong>
    <em class="ad-kpi-note">{{current?fmt(vo?a.otherRegions:a.college.otherRegions)+' человек':'История не предоставлена'}}</em>
    <span v-if="current" class="ad-kpi-spark-wrap" :style="{'--spark-y':miniSparkEnd([0,vo?34:18])/36*100+'%'}"><svg class="ad-kpi-spark" viewBox="0 0 100 36" preserveAspectRatio="none" aria-hidden="true"><path class="ad-kpi-spark-area" :d="miniSparkArea([0,vo?34:18])"/><path class="ad-kpi-spark-line" :d="miniSpark([0,vo?34:18])"/></svg><i class="ad-kpi-spark-dot" aria-hidden="true"></i></span>
   </UiButton>
   <UiButton class="ad-kpi ad-kpi--quota" :class="{'ad-kpi-missing':!current}" @click="vo?navigate({section:'composition',composition:'quotas'}):openQuota('priority')">
    <span class="ad-kpi-head"><b>{{vo?'Приём по квотам':'Первоочередной приём'}}</b><i><Icon name="users" :size="21"/></i></span>
    <strong>{{current?fmt(quotaTotal):'Нет данных'}}</strong>
    <em class="ad-kpi-note">{{current?(vo?fmt(svoQuota)+' — СВО и семьи · '+fmt(svoShare)+'% квот':'+14,1% · к прошлому году'):'История не предоставлена'}}</em>
    <span v-if="current" class="ad-kpi-spark-wrap" :style="{'--spark-y':miniSparkEnd(vo?[0,svoShare]:[100,100+a.college.priority.change])/36*100+'%'}"><svg class="ad-kpi-spark" viewBox="0 0 100 36" preserveAspectRatio="none" aria-hidden="true"><path class="ad-kpi-spark-area" :d="miniSparkArea(vo?[0,svoShare]:[100,100+a.college.priority.change])"/><path class="ad-kpi-spark-line" :d="miniSpark(vo?[0,svoShare]:[100,100+a.college.priority.change])"/></svg><i class="ad-kpi-spark-dot" aria-hidden="true"></i></span>
   </UiButton>
  </div>
  <div class="ad-overview-grid">
   <UiPanel v-if="vo" class="ad-trend-panel" title="Динамика зачисления" description="2023–2026 · все формы обучения · человек"><LineChart :values="a.enrollmentHistory" :labels="a.years" interactive @select="yearPoint"/><p>−104 человека к 2025 году</p></UiPanel>
   <UiPanel v-else title="Масштаб набора в колледжи" description="2026 · сравнение с прошлым годом из источника"><div class="ad-summary-pair"><div><strong>1,39 тыс.</strong><span>зачислено · +3,3%</span></div><div><strong>8,3 тыс.</strong><span>заявлений · +2,6%</span></div></div><p class="ad-empty">Нет данных за предыдущие годы.</p></UiPanel>
   <UiPanel title="Зачисление по подразделениям" :description="vo?'Топ-5 · очная форма · 2026':'Пять колледжей · 2026 · форма не указана'"><div v-if="current" class="ad-top-list"><UiButton v-for="(d,index) in top" :key="d.id" :style="instituteStyle(d.id)" @click="openDepartment(d.id)"><span class="ad-rank">{{index+1}}</span><InstituteBadge v-if="vo" :id="d.id"/><span v-else>{{d.short}}</span><span class="ad-top-track"><i :style="{width: d.enrolled/top[0]!.enrolled*100+'%'}"></i></span><strong>{{fmt(d.enrolled)}}</strong><Icon name="right" :size="15"/></UiButton></div><p v-else class="ad-empty">Нет разбивки за {{s.year}} год. </p><UiButton class="ad-text-link" @click="navigate({section:'departments',selected:'all'})">Все подразделения <Icon name="right" :size="16"/></UiButton></UiPanel>
   <UiPanel v-if="vo" class="ad-trend-panel" title="Подготовка поступивших" description="ЕГЭ · бюджет · 2023–2026 · баллы"><LineChart :values="a.scoreHistory" :labels="a.years" color="#775bc8"/><div class="ad-inline-summary"><span v-if="current"><b>5</b> победителей и призёров олимпиад</span><UiButton class="ad-text-link" @click="navigate({section:'quality'})">Качество набора <Icon name="right" :size="16"/></UiButton></div></UiPanel>
   <UiPanel v-else title="Программы — лидеры по заявлениям" description="Топ-6 · СПО · 2026"><ProgramList :items="programRows('СПО','applications')" college @program="openProgram" @department="openShort"/></UiPanel>
   <UiPanel v-if="vo" title="Средний балл ЕГЭ по вузам" :description="`Бюджет · ${s.year} · вузы железнодорожного транспорта`"><UniversityScores v-if="current"/><p v-else class="ad-empty">Нет сравнения вузов за {{s.year}} год.</p><UiButton class="ad-text-link" @click="navigate({section:'quality'})">Качество набора <Icon name="right" :size="16"/></UiButton></UiPanel>
   <UiPanel v-else title="Первоочередной приём" :description="`${s.year} · зачислено, человек`"><template v-if="current"><UiButton v-for="q in quotaRows" :key="q.id" class="ad-quota" :class="{'ad-target':q.id==='target'}" @click="openQuota(q.id)"><span><b>{{q.name}}</b><small>{{q.label}}</small></span><strong>{{q.value}}<small v-if="q.change!==null">{{q.change>0?'+':''}}{{fmt(q.change)}}%</small></strong><Icon name="right" :size="16"/></UiButton><p class="ad-muted">Изменение к прошлому году</p></template><p v-else class="ad-empty">История по квотам за {{s.year}} год не предоставлена.</p></UiPanel>
   <UiPanel class="ad-full-width" title="География набора" :description="`${s.year} · зачисленные`"><Geography v-if="current" :level="s.level" @region="openRegion"/><p v-else class="ad-empty">Нет географической разбивки за {{s.year}} год.</p><div class="ad-inline-summary"><UiButton class="ad-text-link" @click="navigate({section:'composition',composition:'foreign'})">Иностранный набор · нет данных <Icon name="right" :size="16"/></UiButton></div></UiPanel>
  </div>
  <details v-if="vo&&current" class="ad-scenarios"><summary>Анализ результатов</summary><div v-for="scenarioItem in rules.scenarios" :key="scenarioItem.destination"><h3>{{scenarioItem.observation}}</h3><p>{{scenarioItem.action}}</p><UiButton class="ad-text-link" @click="scenario(scenarioItem.destination)">{{scenarioItem.path}} <Icon name="right" :size="16"/></UiButton></div></details>
 </template>

 <template v-else-if="s.section==='departments'">
  <UiPanel class="ad-departments-panel">
   <template #header>
    <div class="ad-departments-heading">
     <div><h2>Приём по подразделениям</h2><p>{{s.year}} · {{vo?'очная форма':'форма обучения в исходнике не указана'}}</p></div>
     <div class="ad-departments-controls">
      <label class="ad-department-filter ad-department-sort"><span>Подразделение</span><UiSelect v-model="state.selected" aria-label="Подразделение"><option value="all">Все подразделения</option><option v-for="d in departmentOptions" :key="d.id" :value="d.id">{{d.short}} · {{d.name}}</option></UiSelect></label>
      <label class="ad-department-sort"><span>Сортировка</span><UiSelect v-model="state.sort" aria-label="Сортировка подразделений"><option value="desc">По зачислению ↓</option><option value="asc">По зачислению ↑</option></UiSelect></label>
     </div>
    </div>
   </template>
   <div class="ad-department-summary">
    <div><span class="ad-department-summary-icon"><Icon name="users" :size="25"/></span><div><strong>{{fmt(departmentTotal)}}</strong><span>зачислено</span></div><small>{{fmt(departmentCoverage)}}% от общего приёма</small></div>
    <div><span class="ad-department-summary-icon"><Icon name="institutes" :size="25"/></span><div><strong>{{departmentOptions.length}}</strong><span>{{departmentOptions.length===5?'колледжей':'подразделений'}}</span></div></div>
    <div><span class="ad-department-summary-icon"><Icon name="trophy" :size="25"/></span><div><strong>{{departmentLeader?.short}} · {{fmt(departmentLeader?.enrolled??0)}}</strong><span>лидер приёма</span></div><small>{{fmt((departmentLeader?.enrolled??0)/departmentTotal*100)}}% доступной разбивки</small></div>
   </div>
   <div class="ad-department-list-wrap">
    <div class="ad-department-list">
     <div class="ad-department-list-head" aria-hidden="true"><span>№</span><span>Подразделение</span><span>Зачислено</span><span>К численности</span><span>Всего</span><span></span></div>
     <table class="admission-bars" role="presentation"><tbody>
      <tr v-for="(d,index) in rows" :key="d.id"><td>
       <UiButton class="ad-department-row" :class="{'is-leading':d.id===departmentLeader?.id}" :style="vo?instituteStyle(d.id):{}" @click="openDepartment(d.id)">
        <span class="ad-department-number">{{index+1}}</span>
        <span class="ad-department-identity"><InstituteBadge v-if="vo" :id="d.id" symbol-only/><span v-else class="ad-department-college-icon"><Icon name="institutes" :size="20"/></span><span class="ad-department-copy"><span><b>{{d.short}}</b><small>{{d.name}}</small></span><span class="ad-department-track"><i :style="{width:d.enrolled/departmentMax*100+'%'}"></i></span></span></span>
        <strong class="ad-department-enrolled">{{fmt(d.enrolled)}}</strong><span class="ad-department-share">{{fmt(departmentShare(d.enrolled,d.students))}}%</span><span class="ad-department-students">{{fmt(d.students)}}</span><Icon class="ad-department-arrow" name="right" :size="18"/>
       </UiButton>
      </td></tr>
     </tbody></table>
    </div>
   </div>
   <p v-if="vo" class="ad-department-note">7 060 — все формы обучения. Список показывает все {{departmentOptions.length}} подразделений из доступной разбивки по очной форме.</p>
   <p v-else class="ad-department-note">По колледжам — 1 386, по географии — 1 390. Итог уточняется; показаны все {{departmentOptions.length}} колледжей.</p>
  </UiPanel>
 </template>

 <template v-else-if="s.section==='programs'"><div class="ad-filters"><label>Подразделение<UiSelect v-model="state.selected" aria-label="Подразделение"><option value="all">Все подразделения</option><option v-for="d in departmentOptions" :key="d.id" :value="d.id">{{d.short}}</option></UiSelect></label><UiTabs v-model="state.mode" label="Режим программ" :items="[{value:'leaders',label:'Лидеры'},{value:'new',label:'Новые программы',disabled:!vo}]"/><label v-if="s.mode==='leaders'">Показатель<UiSelect v-model="state.metric" aria-label="Рейтинг программ"><option value="applications">По заявлениям</option><option value="competition">По конкурсу на бюджет</option><option v-if="vo" value="score">По баллу ЕГЭ · технические</option></UiSelect></label></div><template v-if="s.mode==='new'"><UiPanel v-for="programLevel in ['Базовое высшее образование','Специализированное высшее образование']" :key="programLevel" :title="programLevel" description="Новые программы · 2026"><ProgramList :items="programs.filter(p=>p.level===programLevel)" @program="openProgram" @department="openShort"/></UiPanel><p class="ad-empty">Статистика набора по новым программам пока недоступна.</p></template><UiPanel v-else :title="metricLabels[s.metric]" :description="`${vo?'Топ-5':'Топ-6'} · ${s.year} · ${metricUnits[s.metric]} · ${s.selected==='all'?'все подразделения':selectedName}`"><template v-if="!vo&&s.metric==='competition'"><div class="ad-detail-number"><strong>7,2</strong><span>чел./место · общий конкурс на бюджет СПО</span></div><p class="ad-empty">Рейтинг конкурса по программам СПО не предоставлен. Доступен только общий показатель.</p></template><ProgramList v-else :items="programs" :college="!vo" @program="openProgram" @department="openShort"/><p class="ad-muted">Показаны только программы-лидеры.</p><p v-if="s.metric==='applications'&&vo" class="ad-muted">Единица исходного рейтинга — «чел.»; методика подсчёта уточняется.</p></UiPanel></template>

 <template v-else-if="s.section==='quality'"><template v-if="vo"><div class="ad-summary-pair ad-quality-totals"><div><strong>{{fmt(exam!)}}</strong><span>ЕГЭ · бюджет · {{s.year}}</span></div><div><strong>{{current?fmt(a.scoreAll):'Нет данных'}}</strong><span>ЕГЭ · бюджет и платное · {{s.year}}</span></div></div><UiPanel class="ad-trend-panel" title="Динамика ЕГЭ на бюджете" description="2023–2026 · баллы"><LineChart :values="a.scoreHistory" :labels="a.years" color="#775bc8"/></UiPanel><template v-if="current"><UiPanel title="Вузы железнодорожного транспорта" description="Средний балл ЕГЭ · бюджет · 2026"><UniversityScores/><p class="ad-muted">Россия: 70,1 балла · 2025 год. Данные за другой период.</p></UiPanel><UiPanel title="Технические программы — лидеры по ЕГЭ" description="Топ-5 · бюджет · 2026 · баллы"><ProgramList :items="programRows('ВО','score')" @program="openProgram" @department="openShort"/></UiPanel><UiPanel title="Индивидуальные достижения"><div class="ad-summary-pair"><div><strong>5</strong><span>победителей и призёров олимпиад</span></div><div><strong>300</strong><span>максимальный конкурсный балл</span></div></div><p>290 баллов ЕГЭ + 10 за достижения. ВИШ · «{{rules.quality.program}}».</p></UiPanel></template><p v-else class="ad-empty">Сравнение вузов, технический рейтинг, олимпиадники и максимальный конкурсный балл за {{s.year}} год не предоставлены.</p></template><UiPanel v-else title="Нет данных о качестве набора СПО"><p>В исходных итогах СПО нет показателей ЕГЭ и аналогичного рейтинга подготовки. Показатели ВО не переносятся.</p></UiPanel></template>

 <template v-else-if="s.section==='composition'"><UiTabs v-model="state.composition" label="Состав набора" :items="[{value:'quotas',label:vo?'Квоты':'Первоочередной приём'},{value:'geography',label:'География России'},{value:'foreign',label:'Иностранный набор'}]"/><UiPanel v-if="s.composition==='quotas'" :title="vo?'Категории приёма':'Первоочередной приём'" :description="`${s.year} · ${s.level} · зачислено, человек`"><UiButton v-for="q in quotaRows" :key="q.id" class="ad-quota" :class="{'ad-target':q.id==='target'}" @click="openQuota(q.id)"><span><b>{{q.name}}</b><small>{{q.label}}</small></span><strong>{{q.value}}<small v-if="q.change!==null">{{q.change>0?'+':''}}{{fmt(q.change)}}%</small></strong><Icon name="right" :size="17"/></UiButton></UiPanel><UiPanel v-else-if="s.composition==='geography'" title="География России" :description="`${s.year} · зачислено, человек`"><Geography :level="s.level" @region="openRegion"/><p v-if="vo" class="ad-muted">Показаны пять регионов с наибольшим набором.</p><p v-if="!vo" class="ad-muted">По географии — 1 390, по колледжам — 1 386. Итог уточняется.</p></UiPanel><UiPanel v-else title="Иностранный набор" :description="`${s.year} · гражданство`"><h3>Нет данных</h3><p>{{foreignText}}</p><div class="ad-availability"><span>Зачисленные <b>Нет данных</b></span><span>Доля набора <b>Нет данных</b></span><span>Число стран <b>Нет данных</b></span></div><p>Разбивка по странам, подразделениям и программам пока недоступна.</p></UiPanel></template>
 <footer class="ad-source"><span>{{sourceNote}} · {{s.year}} · {{s.level}}</span><span>Источник и определения — в «О данных и расчётах»</span></footer>
</div></template>
