<script setup lang="ts">
import {UiMetric,UiButton,UiPanel,UiBadge,UiTabs} from './ui';
import {ref} from 'vue';
import {finance as f,science as s,research,strategy,fmt} from '../data';
import Icon from './Icon.vue';import LineChart from './LineChart.vue';import DonutChart from './DonutChart.vue';
defineProps<{page:string}>();const emit=defineEmits<{topic:[id:string,section?:number]}>();const flow=ref('income');const section=ref('overview');
</script>
<template><template v-if="page==='finance'"><div class="kpi-grid"><UiMetric interactive label="Доходы · план 2026" :value="fmt(f.income)" unit="млн ₽" icon="finance" @click="emit('topic','finance-income')">Структура поступлений</UiMetric><UiMetric interactive label="Расходы · план 2026" :value="fmt(f.expenses)" unit="млн ₽" icon="finance" @click="emit('topic','finance-expenses')">Направления использования</UiMetric><UiMetric interactive label="Прибыль · план 2026" :value="fmt(f.profit.at(-1)!)" unit="млн ₽" icon="trend" @click="emit('topic','profit-use')">Динамика и распределение</UiMetric><UiMetric interactive label="Развитие · 2026" value="5 576,8" unit="млн ₽" icon="projects" @click="emit('topic','strategy-overview')">Государственные программы</UiMetric></div><UiTabs v-model="section" label="Финансовая аналитика" :items="[{value:'overview',label:'Обзор бюджета'},{value:'funding',label:'Программы развития'}]"/>
<div v-if="section==='overview'" class="two-col focus-panels"><UiPanel><div class="panel-head"><h2>Структура бюджета</h2><UiTabs v-model="flow" label="Поток бюджета" :items="[{value:'income',label:'Доходы'},{value:'expenses',label:'Расходы'}]"/></div><DonutChart :key="flow" :items="flow==='income'?f.incomeItems:f.expenseItems" unit="млн ₽" :show-shares="false"/><div class="budget-tools"><UiButton variant="ghost" size="sm" @click="emit('topic','finance-'+flow)">Детализация статей <Icon name="right"/></UiButton><details class="data-note"><summary>Согласование итогов</summary><p>{{f.note}}</p></details></div></UiPanel><UiPanel title="Динамика прибыли" description="млн ₽ · 2026 — план"><LineChart :values="f.profit" :labels="f.profitYears"/><div class="chart-insight"><b>{{fmt(f.profit.at(-1)!)}} млн ₽</b><span>плановая прибыль на 2026 год</span></div><UiButton class="subtle-link focus-more" @click="emit('topic','profit-use')">На что направлена прибыль <Icon name="right"/></UiButton></UiPanel></div>
<UiPanel v-else class="focus-scroll" title="Финансирование стратегического развития" description="Годовой бюджет, период и состав мероприятий"><div class="table-scroll"><table><thead><tr><th>Программа</th><th>2026, млн ₽</th><th>За период, млн ₽</th><th>Период</th></tr></thead><tbody><tr v-for="r in strategy" :key="r.id"><td><UiButton class="program-open" @click="emit('topic',r.id)">{{r.title}} <Icon name="arrow" :size="16"/></UiButton></td><td><b>{{fmt(r.year)}}</b></td><td>{{fmt(r.total)}}</td><td>{{r.period}}</td></tr></tbody></table></div></UiPanel></template>
<template v-else><div class="kpi-grid"><UiMetric interactive label="НИОКР · план 2026" :value="fmt(s.total)" unit="млн ₽" icon="science" @click="emit('topic','science-detail')">×2 за 2024–2026 годы</UiMetric><UiMetric interactive label="Компании-партнёры" :value="s.partners" icon="users" @click="emit('topic','competence')">Научная кооперация</UiMetric><UiMetric interactive label="Диссертационные советы" :value="String(s.councils)" icon="book" @click="emit('topic','science-detail',2)">{{s.specialties}} научных специальностей</UiMetric><UiMetric interactive label="Целевой объём · 2036" :value="'> '+s.target" unit="млрд ₽" icon="trend" @click="emit('topic','science-detail')">Стратегический ориентир</UiMetric></div><UiTabs v-model="section" label="Научная аналитика" :items="[{value:'overview',label:'Масштаб и тематика'},{value:'funding',label:'Финансирование и разработки'}]"/>
<div v-if="section==='overview'" class="two-col focus-panels"><UiPanel title="Объём исследований" description="Объём НИОКР · млрд ₽ · 2026 — план"><LineChart :values="s.volumes" :labels="s.years"/><UiButton variant="secondary" @click="emit('topic','science-detail')">Научная модель и подготовка кадров <Icon name="right"/></UiButton></UiPanel><UiPanel title="Тематика исследований"><template #action><UiBadge>2026</UiBadge></template><DonutChart :items="s.topics" unit="%"/></UiPanel></div>
<div v-else class="two-col focus-panels"><UiPanel title="Источники финансирования"><UiButton class="quota-row action-row" v-for="(t,index) in s.funding" :key="t.name" @click="emit('topic','science-detail',0)"><span>{{t.name}}</span><b>{{fmt(t.value)}} млн ₽</b><Icon name="arrow" :size="16"/></UiButton><div class="insight"><Icon name="book"/>За 2025 год: 7 докторских и 26 кандидатских защит.</div><UiButton class="subtle-link focus-more" @click="emit('topic','research-portfolio')">Все разработки по программам <Icon name="right"/></UiButton></UiPanel><UiPanel title="Разработки с потенциалом коммерциализации" description="Годовой и общий объём учитываются раздельно"><UiButton v-for="r in research" :key="r.id" class="quota-row action-row" @click="emit('topic',r.id)"><span>{{r.title}}</span><b>{{fmt(r.value??r.total!)}} млн ₽<small class="program-level">{{r.value===null?'общий объём':'2026 год'}}</small></b><Icon name="arrow" :size="16"/></UiButton></UiPanel></div></template></template>
