<script setup lang="ts">
import {ref,onBeforeUnmount,onMounted} from 'vue';import {UiButton} from './ui';import Icon from './Icon.vue';import type {CampusPoint} from '../campus';
defineProps<{camera:CampusPoint}>();const emit=defineEmits<{close:[]}>();const minimized=ref(false);const x=ref(Math.max(12,window.innerWidth/2-300));const y=ref(Math.max(12,window.innerHeight/2-210));const host=ref<HTMLElement>();let origin:{x:number;y:number;px:number;py:number}|null=null;
function clamp(){if(!host.value)return;const r=host.value.getBoundingClientRect();x.value=Math.max(8,Math.min(x.value,window.innerWidth-r.width-8));y.value=Math.max(8,Math.min(y.value,window.innerHeight-r.height-8));}
function start(e:PointerEvent){if((e.target as Element).closest('button'))return;origin={x:x.value,y:y.value,px:e.clientX,py:e.clientY};e.preventDefault();}
function move(e:PointerEvent){if(!origin)return;x.value=origin.x+e.clientX-origin.px;y.value=origin.y+e.clientY-origin.py;clamp();}
function stop(){origin=null;}
onMounted(()=>{window.addEventListener('pointermove',move);window.addEventListener('pointerup',stop);window.addEventListener('resize',clamp);});onBeforeUnmount(()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',stop);window.removeEventListener('resize',clamp);});
</script>
<template><Teleport to="body"><button v-if="minimized" class="camera-restore" @click="minimized=false"><Icon name="video"/>{{camera.name}} <Icon name="expand"/></button><section v-else ref="host" class="camera-window" role="dialog" :aria-label="camera.name+' · видеонаблюдение'" :style="{left:x+'px',top:y+'px'}"><header @pointerdown="start"><Icon name="video"/><b>{{camera.name}}</b><UiButton aria-label="Свернуть видео" @click="minimized=true">—</UiButton><UiButton aria-label="Закрыть видео" @click="emit('close')"><Icon name="close"/></UiButton></header><div class="camera-mock-view"><div class="mock-corridor"></div><span>{{camera.name}}</span><div><Icon name="video" :size="34"/><b>Камера не подключена</b><p>Видеопоток недоступен</p></div></div><footer>Перетащите окно за заголовок · размер — за нижний угол</footer></section></Teleport></template>
