<script setup lang="ts">
import {computed,nextTick,onBeforeUnmount,ref} from 'vue';
import guide from '../../data/design-system.json';
import {tokens} from '../design/tokens';
import {institutes,overview,admissions,fmt,type Institute} from '../data';
import {instituteIdentity} from '../identity';
import Icon from './Icon.vue';
import InstituteBadge from './InstituteBadge.vue';
import LineChart from './LineChart.vue';
import DonutChart from './DonutChart.vue';
import PageControls from './PageControls.vue';
import {UiButton,UiBadge,UiPanel,UiInput,UiSelect,UiTabs,UiSwitch,UiEmptyState,UiMetric,UiDialog} from './ui';
const emit=defineEmits<{institute:[institute:Institute];topic:[id:string]}>();
const sections=[{id:'overview',title:'Характер и принципы',icon:'design'},{id:'foundations',title:'Визуальные основы',icon:'layers'},{id:'components',title:'Компоненты',icon:'projects'},{id:'identity',title:'Идентичность институтов',icon:'institutes'},{id:'data',title:'Данные и графики',icon:'trend'},{id:'ux',title:'UX-сценарии',icon:'map'},{id:'access',title:'Доступность',icon:'shield'},{id:'engineering',title:'Для разработки',icon:'source'}];
const section=ref('overview');const componentGroup=ref('actions');const foundationTab=ref('palette');const scroller=ref<HTMLElement>();
const current=computed(()=>sections.find(i=>i.id===section.value)!);
const variant=ref<'primary'|'secondary'|'ghost'|'danger'>('primary');const size=ref<'sm'|'md'|'lg'>('md');const disabled=ref(false);const busy=ref(false);const feedback=ref('');const email=ref('');const formError=ref('');const hints=ref(true);const density=ref('comfortable');const sampleTab=ref('overview');const samplePage=ref(0);const dialogOpen=ref(false);let timer:ReturnType<typeof setTimeout>|undefined;
const colorLabels:Record<string,string>={primary:'Основной синий','primary-hover':'Активное действие','primary-soft':'Синий фон',text:'Основной текст',muted:'Вторичный текст',subtle:'Служебная подпись',canvas:'Рабочая среда',surface:'Поверхность',border:'Граница',success:'Положительное состояние','success-soft':'Фон успеха',warning:'Внимание','warning-soft':'Фон внимания',danger:'Ошибка','danger-soft':'Фон ошибки',focus:'Фокус клавиатуры'};
const rules=computed(()=>section.value==='data'?guide.dataRules:section.value==='access'?guide.accessibility:section.value==='engineering'?guide.engineering:guide.foundations);
const code=computed(()=>`<UiButton variant="${variant.value}" size="${size.value}"${disabled.value?' disabled':''}>\n  Открыть аналитику\n</UiButton>`);
async function selectSection(id:string){section.value=id;await nextTick();if(scroller.value){scroller.value.scrollTop=0;if(window.matchMedia('(max-width:760px)').matches)scroller.value.scrollIntoView({block:'start',behavior:'instant'});}}
function tryAction(){if(disabled.value||busy.value)return;busy.value=true;feedback.value='';clearTimeout(timer);timer=setTimeout(()=>{busy.value=false;feedback.value='Готово. Это демонстрация состояния кнопки.';},700);}
function validate(){formError.value=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.value)?'':'Введите адрес в формате name@example.ru';feedback.value=formError.value?'':'Формат адреса проверен. Данные никуда не отправляются.';}
async function copy(value:string){try{await navigator.clipboard.writeText(value);feedback.value=`Скопировано: ${value}`;}catch{feedback.value=`Значение для копирования: ${value}`;}}
onBeforeUnmount(()=>clearTimeout(timer));
</script>
<template>
 <div class="design-system">
  <aside class="ds-nav"><div class="ds-wordmark"><span class="ds-mark"><Icon name="design" :size="24"/></span><div><b>{{guide.name}}</b><small>Система интерфейсов RUT.digital</small></div></div><nav aria-label="Разделы дизайн-системы"><UiButton v-for="(item,i) in sections" :key="item.id" :class="{active:section===item.id}" :aria-current="section===item.id?'page':undefined" @click="selectSection(item.id)"><span class="ds-index">0{{i+1}}</span><span>{{item.title}}</span><Icon name="chevron" :size="15"/></UiButton></nav><div class="ds-version"><i></i>Версия {{guide.version}} · Vue 3 + TypeScript</div><a class="ds-download" href="/design-system.md" download="RUT.digital-дизайн-система.md"><Icon name="download" :size="16"/>Скачать руководство</a></aside>
  <div ref="scroller" class="ds-content" tabindex="0" :aria-label="current.title">
   <header class="ds-section-heading"><div><span class="ds-eyebrow">ERUT / ДИЗАЙН-СИСТЕМА</span><h2>{{current.title}}</h2></div><UiBadge tone="neutral">{{String(sections.findIndex(i=>i.id===section)+1).padStart(2,'0')}} / 08</UiBadge></header>
   <template v-if="section==='overview'">
    <section class="ds-hero"><div class="ds-orbits" aria-hidden="true"></div><UiBadge>Локальная библиотека компонентов</UiBadge><h3>Ясность<br>в движении<span>.</span></h3><p>Единый язык для данных, людей и решений университета. Узнаваемый, спокойный и собранный вокруг главного.</p><div class="ds-hero-actions"><UiButton variant="primary" @click="selectSection('components')">Исследовать компоненты <Icon name="right"/></UiButton><UiButton variant="secondary" @click="selectSection('ux')">Принципы UX</UiButton></div><div class="ds-color-track" aria-hidden="true"><i v-for="i in institutes" :key="i.id" :style="{background:instituteIdentity(i.id).color}"></i></div></section>
    <div class="ds-principles"><UiPanel v-for="(rule,index) in guide.principles" :key="rule.title"><div class="ds-rule-number"><Icon :name="rule.icon" :size="22"/><span>0{{index+1}}</span></div><h3>{{rule.title}}</h3><p>{{rule.text}}</p></UiPanel></div>
    <div class="ds-note"><Icon name="info"/><p>Это живая спецификация: примеры используют те же компоненты, что и рабочие экраны. Компоненты, стили и правила работы интерфейса RUT.digital.</p></div>
   </template>
   <template v-else-if="section==='foundations'">
    <UiTabs v-model="foundationTab" label="Основы дизайна" :items="[{value:'palette',label:'Цвет'},{value:'type',label:'Типографика'},{value:'space',label:'Ритм и движение'}]"/>
    <div v-if="foundationTab==='palette'" class="ds-swatches"><UiButton v-for="(value,key) in tokens.color" :key="key" class="ds-swatch" :aria-label="`Скопировать ${colorLabels[key]} ${value}`" @click="copy(value)"><span :style="{background:value}"></span><b>{{colorLabels[key]}}</b><code>{{value}}</code><small>--er-color-{{key}}</small></UiButton></div>
    <UiPanel v-else-if="foundationTab==='type'" class="ds-type-specimen"><span class="ds-eyebrow">GOLOS TEXT VARIABLE · КИРИЛЛИЦА</span><div class="ds-type-line" v-for="t in [{size:34,name:'Ключевой показатель',text:'32 085'},{size:28,name:'Заголовок страницы',text:'Университет в движении'},{size:20,name:'Заголовок блока',text:'Приёмная кампания'},{size:15,name:'Основной текст',text:'Данные помогают видеть главное и принимать решения.'},{size:14,name:'Подпись контрола',text:'Открыть аналитику'},{size:13,name:'Служебное пояснение',text:'Состояние на сентябрь 2026'}]" :key="t.size"><div><b>{{t.size}} px</b><span>{{t.name}}</span></div><p :style="{fontSize:t.size+'px',fontWeight:t.size>=20?600:400}">{{t.text}}</p></div></UiPanel>
    <div v-else class="ds-grid"><UiPanel title="Шкала расстояний"><div v-for="(value,key) in tokens.space" :key="key" class="ds-space-row"><b>{{value}}</b><i :style="{width:value}"></i><code>space-{{key}}</code></div></UiPanel><UiPanel title="Радиусы и поверхности"><div class="ds-radius-row"><div v-for="(value,key) in tokens.radius" :key="key" :style="{borderRadius:value}"><b>{{value}}</b><small>{{key}}</small></div></div><div class="ds-motion-row" v-for="(value,key) in tokens.motion" :key="key"><span>{{key==='fast'?'Отклик':key==='normal'?'Переключение':'Появление'}}</span><b>{{value}}</b></div></UiPanel></div>
    <div class="ds-rule-list"><article v-for="rule in guide.foundations" :key="rule.title"><h3>{{rule.title}}</h3><p>{{rule.text}}</p></article></div>
   </template>
   <template v-else-if="section==='components'">
    <p class="ds-lead">Не картинки, а рабочие элементы. Меняйте состояние и проверяйте клавиатуру — поведение совпадает с приложением.</p>
    <UiTabs v-model="componentGroup" label="Группы компонентов" :items="[{value:'actions',label:'Действия'},{value:'forms',label:'Формы'},{value:'data',label:'Панели и данные'},{value:'states',label:'Окна и состояния'}]"/>
    <UiPanel v-if="componentGroup==='actions'" class="ds-playground" title="Одна кнопка — все состояния" description="У каждого варианта есть обычное, hover, focus, loading и disabled состояния."><div class="ds-control-row"><UiSelect v-model="variant" label="Назначение"><option value="primary">Основное</option><option value="secondary">Вторичное</option><option value="ghost">Служебное</option><option value="danger">Опасное</option></UiSelect><UiSelect v-model="size" label="Размер"><option value="sm">Компактный · 36</option><option value="md">Основной · 44</option><option value="lg">Крупный · 52</option></UiSelect><UiSwitch v-model="disabled" label="Недоступна"/></div><div class="ds-demo-stage"><UiButton :variant="variant" :size="size" :disabled="disabled" :loading="busy" @click="tryAction"><Icon v-if="!busy" name="arrow"/>{{busy?'Выполняется':'Открыть аналитику'}}</UiButton></div><pre class="ds-code">{{code}}</pre><div class="ds-example-row"><UiButton variant="primary" @click="feedback='Выбран вариант: основное действие.'">Основное действие</UiButton><UiButton variant="secondary" @click="feedback='Выбран вариант: вторичное.'">Вторичное</UiButton><UiButton variant="ghost" @click="feedback='Выбран вариант: служебное.'">Служебное</UiButton><UiButton variant="danger" @click="feedback='Выбран вариант: опасное.'">Опасное</UiButton><UiButton variant="secondary" disabled>Недоступно</UiButton></div></UiPanel>
    <UiPanel v-if="componentGroup==='forms'" title="Форма с понятной обратной связью"><form class="ds-form" :class="{'ds-form--compact':density==='compact'}" @submit.prevent="validate"><UiInput v-model="email" label="Электронная почта" placeholder="name@example.ru" :error="formError" :hint="hints?'Демонстрация проверки формата, без отправки данных.':undefined" @update:model-value="formError=''"><template #prefix><Icon name="mail"/></template></UiInput><UiSelect v-model="density" label="Представление"><option value="comfortable">Основное</option><option value="compact">Компактное</option></UiSelect><UiSwitch v-model="hints" label="Показывать пояснения" description="Мгновенная обратимая настройка"/><div class="ds-example-row"><UiButton variant="primary" type="submit">Проверить формат</UiButton><UiButton variant="ghost" @click="email='';formError='';feedback=''">Сбросить</UiButton></div></form><div class="ds-note"><Icon name="info"/><p>Обязательная подпись остаётся видимой после ввода. Ошибка указывает, что исправить; успешная проверка не означает отправку или регистрацию.</p></div></UiPanel>
    <template v-if="componentGroup==='data'"><div class="ds-grid"><UiMetric label="Обучающихся" :value="fmt(overview.students)" icon="users">ВО, СПО и гимназия</UiMetric><UiMetric label="Средний балл ЕГЭ" :value="fmt(admissions.score)" icon="trend" unit="балла">Бюджет · 2026</UiMetric></div><UiPanel title="Выбор среза"><UiTabs v-model="sampleTab" label="Пример переключения" :items="[{value:'overview',label:'Обзор'},{value:'admissions',label:'Приём'},{value:'disabled',label:'Недоступно',disabled:true}]"/><p class="ds-demo-copy">{{sampleTab==='overview'?'Обзор показывает ключевой показатель и его контекст.':'Выбран срез приёма. Изменяется содержимое, расположение навигации сохраняется.'}}</p><div class="ds-example-row"><UiBadge tone="neutral">Категория</UiBadge><UiBadge tone="info" dot>План 2026</UiBadge><UiBadge tone="success" dot>Готово</UiBadge><UiBadge tone="warning" dot>Требует внимания</UiBadge><UiBadge tone="danger" dot>Ошибка</UiBadge></div></UiPanel><UiPanel title="Пагинация"><div class="ds-badge-list"><InstituteBadge v-for="i in institutes.slice(samplePage*4,(samplePage+1)*4)" :key="i.id" :id="i.id"/></div><PageControls v-model:page="samplePage" :total="institutes.length" :size="4" label="Пример пагинации"/></UiPanel></template>
    <template v-if="componentGroup==='states'"><UiPanel title="Большая карточка" description="Почти весь экран, блокировка фона и возврат к месту открытия."><UiButton variant="primary" @click="dialogOpen=true">Открыть пример окна <Icon name="expand"/></UiButton></UiPanel><UiPanel><UiEmptyState title="Нет подходящих результатов" description="Ничего не потеряно. Измените запрос или сбросьте фильтр."><UiButton variant="secondary" @click="feedback='Фильтры в примере сброшены.'">Сбросить фильтры</UiButton></UiEmptyState></UiPanel><div class="ds-state-message"><Icon name="video"/><div><b>Трансляция не подключена</b><p>Отсутствие источника обозначается явно. При отсутствии подключения показывается статус источника.</p></div></div></template>
    <div class="ds-api-list"><h3>Контракты компонентов</h3><details v-for="component in guide.components" :key="component.name"><summary><code>{{component.name}}</code><span>{{component.title}}</span><Icon name="down" :size="16"/></summary><p>{{component.usage}}</p><div class="ds-props"><b>API</b><code>{{component.props}}</code></div></details></div>
   </template>
   <template v-else-if="section==='identity'"><p class="ds-lead">Десять постоянных идентичностей. Цвет принадлежит институту, а не позиции в списке. Откройте карточку, чтобы увидеть применение в контексте.</p><div class="ds-identities"><UiButton v-for="i in institutes" :key="i.id" :style="{'--identity':instituteIdentity(i.id).color,'--identity-soft':instituteIdentity(i.id).soft}" @click="emit('institute',i)"><InstituteBadge :id="i.id" large/><h3>{{i.name}}</h3><div><span>{{instituteIdentity(i.id).colorName}}</span><code>{{instituteIdentity(i.id).color}}</code><Icon name="arrow" :size="18"/></div></UiButton></div><div class="ds-note"><Icon name="info"/><p>Символы обозначают институты в интерфейсе RUT.digital. В общем корпусе показаны все связанные символы. Изменять оттенок для другого раздела или выбирать цвет по месту в рейтинге нельзя.</p></div></template>
   <template v-else-if="section==='data'"><div class="ds-grid"><UiPanel title="Изменение во времени" description="Средний балл ЕГЭ · бюджет"><LineChart :values="admissions.scoreHistory" :labels="admissions.years"/><UiButton variant="ghost" size="sm" @click="emit('topic','admission-quality')">Подробнее о показателе <Icon name="source" :size="16"/></UiButton></UiPanel><UiPanel title="Части одной суммы" description="География зачисления · 2026"><DonutChart :items="[{name:'Москва и МО',value:admissions.moscow},{name:'Регионы России',value:admissions.otherRegions}]" label="зачислено"/></UiPanel></div><div class="ds-rule-list"><article v-for="rule in guide.dataRules" :key="rule.title"><h3>{{rule.title}}</h3><p>{{rule.text}}</p></article></div></template>
   <template v-else-if="section==='ux'"><div class="ds-flows"><UiPanel v-for="(flow,index) in guide.flows" :key="flow.title"><div class="ds-flow-title"><span>0{{index+1}}</span><h3>{{flow.title}}</h3></div><ol><li v-for="step in flow.steps" :key="step">{{step}}</li></ol></UiPanel></div><div class="ds-note"><Icon name="eye"/><p>Приоритет первого экрана: период → ключевые показатели → текущая задача → следующий шаг. Подробности доступны по действию пользователя. Информацию нельзя прятать без понятной точки входа.</p></div></template>
   <template v-else><div class="ds-rule-list"><article v-for="rule in rules" :key="rule.title"><h3>{{rule.title}}</h3><p>{{rule.text}}</p></article></div><UiPanel v-if="section==='access'" title="Попробуйте без мыши"><p class="ds-demo-copy">Tab переводит фокус, стрелки меняют срез, Escape закрывает окно. Сначала выберите этот блок клавиатурой, затем проверьте переход.</p><UiTabs v-model="sampleTab" label="Проверка клавиатуры" :items="[{value:'overview',label:'Обзор'},{value:'admissions',label:'Приём'},{value:'disabled',label:'Недоступно',disabled:true}]"/><div class="ds-example-row"><UiButton variant="secondary" @click="dialogOpen=true">Проверить диалог</UiButton><UiButton variant="secondary" disabled>Недоступное действие</UiButton></div></UiPanel><UiPanel v-else title="Использование в Vue + TypeScript"><pre class="ds-code">&lt;script setup lang="ts"&gt;
import { ref } from 'vue';
import { UiButton, UiInput } from './components/ui';
const query = ref('');
&lt;/script&gt;

&lt;template&gt;
  &lt;UiInput v-model="query" label="Найти институт" /&gt;
  &lt;UiButton variant="secondary" @click="query = ''"&gt;
    Сбросить поиск
  &lt;/UiButton&gt;
&lt;/template&gt;</pre><p class="ds-demo-copy">Экспорт библиотеки: <code>src/components/ui/index.ts</code><br>Токены: <code>data/design-tokens.json</code><br>Идентичности: <code>data/institute-identities.json</code><br>Тексты руководства: <code>data/design-system.json</code></p></UiPanel></template>
   <footer class="ds-content-footer"><span>RUT.digital · {{guide.name}} {{guide.version}}</span><UiButton variant="ghost" size="sm" @click="selectSection(sections[(sections.findIndex(s=>s.id===section)+1)%sections.length].id)">Следующий раздел <Icon name="right" :size="16"/></UiButton></footer>
  </div>
  <div v-if="feedback" class="ds-feedback" role="status"><Icon name="check" :size="17"/><span>{{feedback}}</span><UiButton class="icon-btn" aria-label="Закрыть сообщение" @click="feedback=''"><Icon name="close" :size="17"/></UiButton></div>
 </div>
 <UiDialog :open="dialogOpen" label="Пример большой карточки" class="ds-demo-dialog" @close="dialogOpen=false"><header><UiBadge>Пример UiDialog</UiBadge><h2>Главное остаётся в центре</h2><p>Та же оболочка используется для институтов, инфраструктуры, событий и проектов.</p></header><div class="ds-dialog-body"><div class="ds-grid"><UiMetric label="Обучающихся" :value="fmt(overview.students)" icon="users">ВО, СПО и гимназия</UiMetric><UiMetric label="Зачислено · 2026" :value="fmt(admissions.enrolled)" icon="admissions">Высшее образование · все формы</UiMetric></div><UiPanel title="Поведение окна"><p>Фон недоступен для взаимодействия. Tab остаётся в пределах карточки. Escape, кнопка закрытия или клик по затемнённому фону закрывают окно и возвращают фокус к месту открытия.</p><UiButton variant="primary" @click="dialogOpen=false">Вернуться в библиотеку <Icon name="right"/></UiButton></UiPanel></div></UiDialog>
</template>
