<script setup lang="ts">
import {computed,ref,watch,onMounted,onBeforeUnmount,nextTick} from 'vue';import CampusMap from './CampusMap.vue';import CampusPopulation from './CampusPopulation.vue';import CameraWindow from './CameraWindow.vue';import InstituteBadge from './InstituteBadge.vue';import Icon from './Icon.vue';import {UiButton,UiTabs} from './ui';
import {campuses,buildings,campusPoints,construction,campusForObject,campusArea,campusStudents,educationTypes,completionColor,campusObjects,type MapMode,type DetailLayer,type Building,type CampusPoint,type Construction} from '../campus';import {fmt,institutes} from '../data';
import MapDestinations from './MapDestinations.vue';
import {instituteStyle} from '../identity';
const props=defineProps<{initialCampusId?:string}>();const emit=defineEmits<{institute:[id:string];campus:[id:string];object:[id:string];navigate:[id:string];admissions:[id:string]}>();
const expanded=ref(false);const scrollPanel=ref<HTMLElement>();const campusId=ref('');const mode=ref<MapMode>('education');const layers=ref<DetailLayer[]>(['buildings']);const sidebarTab=ref('population');const overviewTab=ref('campuses');const feature=ref<Building|CampusPoint|Construction|null>(null);const featureType=ref<'building'|'point'|'construction'>('building');const camera=ref<CampusPoint|null>(null);
const campus=computed(()=>campuses.find(c=>c.id===campusId.value));const building=computed(()=>featureType.value==='building'?feature.value as Building|null:null);const point=computed(()=>featureType.value==='point'?feature.value as CampusPoint|null:null);const project=computed(()=>featureType.value==='construction'?feature.value as Construction|null:null);
const layerChoices:{id:DetailLayer;name:string}[]=[{id:'buildings',name:'Здания'},{id:'gates',name:'КПП'},{id:'food',name:'Кафе и столовые'},{id:'cameras',name:'Камеры'}];
const campusBuildings=computed(()=>buildings.filter(b=>b.campusId===campusId.value));
const campusInstitutes=computed(()=>institutes.filter(i=>campus.value?.objectIds.includes(i.objectId)||campusBuildings.value.some(b=>b.instituteIds.includes(i.id))));
const visiblePoints=computed(()=>campusPoints.filter(p=>p.campusId===campusId.value));
const totalStudents=campuses.reduce((sum,c)=>sum+(campusStudents(c.id)??0),0);
const campusTabs=computed(()=>[{value:'population',label:'Обучающиеся'},{value:'buildings',label:'Корпуса'},{value:'institutes',label:'Подразделения'},{value:'services',label:'Сервисы'}]);
function escapeMap(e:KeyboardEvent){if(e.key!=='Escape')return;if(feature.value){feature.value=null;e.stopPropagation();}else if(expanded.value)expanded.value=false;}
onMounted(()=>window.addEventListener('keydown',escapeMap));onBeforeUnmount(()=>window.removeEventListener('keydown',escapeMap));
watch([sidebarTab,overviewTab,campusId],async()=>{await nextTick();if(scrollPanel.value)scrollPanel.value.scrollTop=0;});
function serviceIcon(kind:string){return kind==='cameras'?'video':kind==='gates'?'shield':'pin';}
function showService(p:CampusPoint){if(!layers.value.includes(p.kind))layers.value=[...layers.value,p.kind];openPoint(p);}
function leaveMap(id:string){expanded.value=false;emit('navigate',id);}
function selectCampus(id:string){campusId.value=id;feature.value=null;camera.value=null;layers.value=['buildings'];sidebarTab.value='population';emit('campus',id);}
watch(()=>props.initialCampusId,id=>{const target=campusForObject(id??'')?.id??id??'';if(target!==campusId.value)selectCampus(target);},{immediate:true});
watch(mode,(value,previous)=>{if(value==='construction'||previous==='construction')selectCampus('');});
function toggleLayer(id:DetailLayer){layers.value=layers.value.includes(id)?layers.value.filter(x=>x!==id):[...layers.value,id];feature.value=null;}
function openBuilding(value:Building){if(!layers.value.includes('buildings'))layers.value=[...layers.value,'buildings'];featureType.value='building';feature.value=value;}
function openPoint(value:CampusPoint){if(value.kind==='cameras'){camera.value=value;return;}featureType.value='point';feature.value=value;}
function openProject(value:Construction){featureType.value='construction';feature.value=value;}
</script>
<template><div class="infrastructure-workspace" :class="{'map-expanded':expanded}"><div class="map-context-bar"><nav aria-label="Навигация по карте"><UiButton @click="selectCampus('')" :aria-current="!campus?'page':undefined"><Icon name="map" :size="16"/>Все кампусы</UiButton><template v-if="campus"><Icon name="chevron" :size="14"/><span>{{campus.name}}</span></template></nav><div class="map-context-actions"><select aria-label="Перейти к кампусу" :value="campusId" @change="selectCampus(($event.target as HTMLSelectElement).value)"><option value="">Выбрать кампус</option><option v-for="c in campuses" :key="c.id" :value="c.id">{{c.name}}</option></select><UiButton :aria-label="expanded?'Свернуть карту':'Развернуть карту'" :aria-pressed="expanded" @click="expanded=!expanded"><Icon :name="expanded?'close':'expand'" :size="18"/></UiButton></div></div><div class="campus-layer-toolbar"><UiTabs v-model="mode" label="Слои карты" :items="[{value:'education',label:'Виды образования'},{value:'students',label:'По кол-ву обучающихся'},{value:'area',label:'По площади'},{value:'construction',label:'Строящиеся объекты'}]"/></div> <div v-if="campus" class="campus-detail-layers"><label v-for="layer in layerChoices" :key="layer.id"><input type="checkbox" :checked="layers.includes(layer.id)" @change="toggleLayer(layer.id)"/>{{layer.name}}</label></div><div class="campus-workbench"><section class="campus-map-stage"><CampusMap :campus-id="campusId" :mode="mode" :detail-layers="layers" :selected-building-id="building?.id" @campus="selectCampus" @building="openBuilding" @point="openPoint" @institute="emit('institute',$event)" @construction="openProject"/>

 <div v-if="!campus" class="campus-map-legend"><template v-if="mode==='education'"><span v-for="type in educationTypes" :key="type.name"><i :style="{background:type.color}"></i>{{type.name}}</span><span><i style="background:#7b8da8"></i>Без категории</span></template><template v-else-if="mode==='construction'"><span><i style="background:#e15757"></i>до 40%</span><span><i style="background:#e7b438"></i>40–79%</span><span><i style="background:#2d9e75"></i>от 80%</span></template><template v-else><span class="scale-gradient"></span><span>Меньше → больше</span></template></div>
 <section v-if="feature" class="map-feature-card" :aria-label="feature.name"><header><UiButton aria-label="Закрыть мини-карточку" @click="feature=null"><Icon name="close"/></UiButton></header><h3>{{feature.name}}</h3><p v-if="building?.geometrySource" class="map-feature-address">{{building.geometrySource.address}}</p><template v-if="building"><p>{{building.area===null?'Площадь уточняется':fmt(building.area)+' м²'}}</p><span v-if="building.construction" class="construction-tag">Строящийся корпус</span><div class="building-institutes"><UiButton v-for="id in building.instituteIds" :key="id" @click="emit('institute',id)"><InstituteBadge :id="id"/><Icon name="arrow" :size="15"/></UiButton></div><p v-if="!building.instituteIds.length">Размещение институтов не указано</p><UiButton v-if="building.objectId" class="map-dossier-link" variant="secondary" @click="emit('object',building.objectId)">Подробнее об объекте <Icon name="arrow" :size="16"/></UiButton><details v-if="building.mockFields.length||building.geometrySource||building.geometryUnavailable" class="map-data-details"><summary>О данных</summary><p v-if="building.mockFields.length">Условные сведения: {{building.mockFields.join(', ').toLowerCase()}}.</p><a v-if="building.geometrySource" class="geometry-source" :href="building.geometrySource.url" target="_blank" rel="noopener">Контур: OpenStreetMap ↗<span>{{building.geometrySource.address}}</span></a><small v-if="building.geometryUnavailable">Точный контур пока не установлен; на плане не отображается.</small></details></template><template v-if="point"><p><Icon name="calendar" :size="17"/>{{point.hours}}</p><p v-if="point.operator">{{point.operator}}</p><details class="map-data-details"><summary>О данных</summary><p>Расположение и расписание приведены для иллюстрации работы сервиса<span v-if="point.operator">; оператор условный</span>.</p></details></template><template v-if="project"><strong class="construction-percent" :style="{color:completionColor(project.completion)}">{{project.completion}}%</strong><p>Ввод: {{project.year}} год</p><details class="map-data-details"><summary>О данных</summary><p>Условные сведения: {{project.mockFields.join(', ').toLowerCase()}}. Название и срок ввода взяты из материалов университета.</p></details><UiButton v-if="project.campusId" variant="secondary" @click="selectCampus(project.campusId!)">Открыть кампус <Icon name="right"/></UiButton></template></section>
 </section><aside class="campus-sidebar"><template v-if="campus"><div class="campus-summary"><span>{{campus.city}}</span><h2>{{campus.name}}</h2><p>{{campus.address}}</p><div><b>{{fmt(campusArea(campus.id))}}<small>м² · площадь</small></b><b>{{campusStudents(campus.id)===null?'—':fmt(campusStudents(campus.id)!)}}<small>обучающихся</small></b></div></div><UiTabs v-model="sidebarTab" class="map-inspector-tabs" label="Сведения о кампусе" :items="campusTabs"/><div ref="scrollPanel" class="campus-sidebar-scroll">
 <CampusPopulation v-if="sidebarTab==='population'" :campus-id="campus.id" @institute="emit('institute',$event)"/>
 <template v-else-if="sidebarTab==='buildings'"><p class="map-section-caption">{{campusBuildings.length}} корпусов · выберите для подробностей</p><UiButton v-for="b in campusBuildings" :key="b.id" class="campus-building-row" :class="{'is-selected':building?.id===b.id}" :aria-pressed="building?.id===b.id" @click="openBuilding(b)"><span class="map-row-icon"><Icon name="institutes" :size="20"/></span><div><b>{{b.name}}</b><small>{{b.area===null?'Площадь уточняется':fmt(b.area)+' м²'}}<span v-if="b.geometryUnavailable"> · без контура</span></small></div><Icon name="chevron" :size="16"/></UiButton></template>
 <template v-else-if="sidebarTab==='institutes'"><div v-for="i in campusInstitutes" :key="i.id" class="map-unit-card" :style="instituteStyle(i.id)"><UiButton class="map-unit-title" @click="emit('institute',i.id)"><InstituteBadge :id="i.id" symbol-only/><span><b>{{i.short}}</b><small>{{i.name}}</small></span><Icon name="arrow" :size="17"/></UiButton><div class="map-unit-metrics"><span><b>{{fmt(i.students)}}</b> студентов · очно</span><span><b>{{fmt(i.enrolled)}}</b> набор 2026</span></div><UiButton class="map-unit-admissions" @click="expanded=false;emit('admissions',i.id)">Аналитика приёма <Icon name="right" :size="14"/></UiButton></div><UiButton v-for="o in campusObjects(campus.id).filter(o=>!campusInstitutes.some(i=>i.objectId===o.id))" :key="o.id" class="campus-building-row" @click="emit('object',o.id)"><div><b>{{o.name}}</b><small>{{fmt(o.area)}} м²</small></div><Icon name="arrow" :size="16"/></UiButton></template>
 <template v-else><p class="map-section-caption">Выбор сервиса включает его слой на карте</p><UiButton v-for="p in visiblePoints" :key="p.id" class="map-service-row" @click="showService(p)"><span class="map-row-icon"><Icon :name="serviceIcon(p.kind)" :size="20"/></span><span><b>{{p.name}}</b><small>{{p.kind==='cameras'?'Видеонаблюдение':p.hours||'Расписание не указано'}}</small></span><Icon name="chevron" :size="16"/></UiButton><p v-if="!visiblePoints.length" class="map-data-empty">Сервисы этого кампуса пока не добавлены.</p></template>
 </div><div class="map-inspector-footer"><span><Icon name="pin" :size="14"/>{{campus.city}}</span><UiButton @click="selectCampus('')"><Icon name="left" :size="14"/>К кампусам</UiButton></div></template>
 <template v-else-if="mode==='construction'"><div class="campus-summary"><span>Развитие инфраструктуры</span><h2>Строящиеся объекты</h2><p>4 проекта · сроки ввода 2026–2031</p></div><div class="campus-sidebar-scroll"><UiButton v-for="p in construction" :key="p.id" class="campus-project-row" @click="openProject(p)"><div><b>{{p.name}}</b><small>{{p.year}} · ввод</small></div><strong :style="{color:completionColor(p.completion)}">{{p.completion}}%</strong></UiButton></div></template>
 <template v-else><div class="campus-summary"><span>Москва и Сочи</span><h2>Университет на карте</h2><div class="map-overview-totals"><span><b>{{campuses.length}}</b> кампусов</span><span><b>{{fmt(totalStudents)}}</b> обучающихся</span></div></div><UiTabs v-model="overviewTab" label="Обзор инфраструктуры" :items="[{value:'campuses',label:'Кампусы'},{value:'population',label:'Контингент'},{value:'destinations',label:'Разделы'}]"/><div ref="scrollPanel" class="campus-sidebar-scroll"><MapDestinations v-if="overviewTab==='destinations'" @navigate="leaveMap"/><CampusPopulation v-else-if="overviewTab==='population'" @institute="emit('institute',$event)"/><UiButton v-else v-for="c in campuses" :key="c.id" class="campus-list-row" @click="selectCampus(c.id)"><div><b>{{c.name}}</b><small>{{mode==='area'?fmt(campusArea(c.id))+' м²':campusStudents(c.id)===null?'Численность не указана':fmt(campusStudents(c.id)!)+' обучающихся'}}</small></div><Icon name="chevron" :size="17"/></UiButton></div></template></aside></div><CameraWindow v-if="camera" :key="camera.id" :camera="camera" @close="camera=null"/></div></template>
